# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TerrainProcessing
                                 A QGIS plugin
 Algorithms to process elevation data in varies formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-09
        copyright            : (C) 2022 by Kartoza
        email                : divan@kartoza.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Kartoza'
__date__ = '2022-06-09'
__copyright__ = '(C) 2022 by Kartoza'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import qgis
import os

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFolderDestination,
    QgsProcessingParameterCrs,
    QgsProcessingOutputFolder,
    QgsProcessingParameterEnum,
    QgsProcessingParameterNumber,
    QgsApplication
)

from qgis.core import (
    QgsProject,
    QgsSettings,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsField,
    QgsCoordinateTransform,
    QgsPointXY,
    QgsFeature,
    QgsCoordinateReferenceSystem,
    QgsGeometry
)

from qgis.analysis import QgsNativeAlgorithms
import processing
from processing.core.Processing import Processing
Processing.initialize()
QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())

from .default import (
    OUTPUT_CRS,
    DESTINATION_FOLDER,
    SOURCE_CRS,
    SOURCE_FOLDER,
    ALLOWED_VECTOR_FORMATS,
    RASTERIZE_OPTIONS,
    NEARSET_NEIGHBOUR,
    POINT_TO_RASTER,
    IDW,
    TIN,
    RASTERIZE_TYPE,
    RESOLUTION,
    RES_DEFAULT,
    DEFAULT_NODATA
)
from .utilities import (
    search_files,
    create_vector_file,
    create_empty_layer
)


class TerrainRasterizePointsAlgorithm(QgsProcessingAlgorithm):
    """
    """

    def initAlgorithm(self, config):
        """
        """

        # NEEDS TO ACTUALLY BE AN INPUT FOLDER OPTION
        self.addParameter(
            QgsProcessingParameterFolderDestination(
                SOURCE_FOLDER,
                self.tr(SOURCE_FOLDER),
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterEnum(
                RASTERIZE_TYPE,
                self.tr(RASTERIZE_TYPE),
                options=RASTERIZE_OPTIONS,
                defaultValue=POINT_TO_RASTER
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                RESOLUTION,
                self.tr(RESOLUTION),
                defaultValue=RES_DEFAULT,
                optional=False,
                type=QgsProcessingParameterNumber.Double
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                RESOLUTION,
                self.tr(RESOLUTION),
                defaultValue=RES_DEFAULT,
                optional=False,
                type=QgsProcessingParameterNumber.Double
            )
        )

        self.addParameter(
            QgsProcessingParameterFolderDestination(
                DESTINATION_FOLDER,
                self.tr(DESTINATION_FOLDER),
                optional=False
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        source_folder = self.parameterAsString(
            parameters,
            SOURCE_FOLDER,
            context
        )
        rasterize_type_index = self.parameterAsEnum(
            parameters,
            RASTERIZE_TYPE,
            context
        )
        rasterize_type = RASTERIZE_OPTIONS[rasterize_type_index]
        spatial_res = self.parameterAsDouble(
            parameters,
            RESOLUTION,
            context
        )
        destination_folder = self.parameterAsString(
            parameters,
            DESTINATION_FOLDER,
            context
        )

        list_files = search_files(source_folder + '/', ALLOWED_VECTOR_FORMATS)
        total = len(list_files)
        completed = 0
        for vector_file in list_files:
            output_file_name = os.path.basename(vector_file)
            destination_file = destination_folder + '/' + output_file_name + '.tif'

            if os.path.exists(destination_file):
                # If the file does exist, it will be skipped
                feedback.setProgressText("Current file will be skipped as it exists: {}".format(vector_file))
            else:
                # File does not exist, processing starts
                feedback.setProgressText("Current file being processed: {}".format(vector_file))

                if rasterize_type == POINT_TO_RASTER:
                    tool = "gdal:rasterize"
                    parameters = {
                        'INPUT': vector_file,
                        'FIELD': 'Elevation',
                        'BURN': -9999,
                        'USE_Z': False,
                        'UNITS': 1,  # 0: Pixels, 1: Coordinate system based
                        'WIDTH': spatial_res,
                        'HEIGHT': spatial_res,
                        'EXTENT': None,
                        'NODATA': -9999,
                        'OPTIONS': '',
                        'DATA_TYPE': 5,
                        'INIT': None,
                        'INVERT': False,
                        'EXTRA': '',
                        'OUTPUT': destination_file
                    }

                    processing.run(tool, parameters)
                elif rasterize_type == NEARSET_NEIGHBOUR:
                    print("NN")
                elif rasterize_type == IDW:
                    print("IDW")
                elif rasterize_type == TIN:
                    print("TIN")
                else:
                    print("UNKOWN TYPE")

            completed = completed + 1
            feedback.setProgress(int((completed / total) * 100))

        print("final merge")

        # Return the results of the algorithm
        return {DESTINATION_FOLDER: destination_folder}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Create raster tiles'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Preprocessing'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return TerrainRasterizePointsAlgorithm()
