# -*- coding: utf-8 -*-

"""
/***************************************************************************
 TerrainProcessing
                                 A QGIS plugin
 Algorithms to process elevation data in varies formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-09
        copyright            : (C) 2022 by Kartoza
        email                : divan@kartoza.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Kartoza'
__date__ = '2022-06-09'
__copyright__ = '(C) 2022 by Kartoza'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os

from qgis.PyQt.QtCore import QCoreApplication, QVariant
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink,
    QgsProcessingAlgorithm,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFolderDestination,
    QgsProcessingParameterCrs,
    QgsProcessingOutputFolder
)

from qgis.core import (
    QgsProject,
    QgsSettings,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsField,
    QgsCoordinateTransform,
    QgsPointXY,
    QgsFeature,
    QgsCoordinateReferenceSystem,
    QgsGeometry
)

from .default import (
    OUTPUT_CRS,
    DESTINATION_FOLDER,
    SOURCE_CRS,
    SOURCE_FOLDER,
    ALLOWED_FORMATS,
    DELIMITER_CHAR,
    COLUMN_COUNT,
    X_INDEX,
    Y_INDEX,
    ELEV_INDEX,
    ELEV_MIN_THRESHOLD,
    ELEV_MAX_THRESHOLD
)
from .utilities import (
    search_files,
    create_vector_file,
    create_empty_layer,
    remove_unwanted_chars
)


class TerrainPointPreprocessingAlgorithm(QgsProcessingAlgorithm):
    """
    """

    def initAlgorithm(self, config):
        """
        """

        # NEEDS TO ACTUALLY BE AN INPUT FOLDER OPTION
        self.addParameter(
            QgsProcessingParameterFolderDestination(
                SOURCE_FOLDER,
                self.tr(SOURCE_FOLDER),
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterCrs(
                SOURCE_CRS,
                self.tr(SOURCE_CRS),
                optional=False
            )
        )

        self.addParameter(
            QgsProcessingParameterCrs(
                OUTPUT_CRS,
                self.tr(OUTPUT_CRS),
                optional=True
            )
        )

        self.addParameter(
            QgsProcessingParameterFolderDestination(
                DESTINATION_FOLDER,
                self.tr(DESTINATION_FOLDER),
                optional=True
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        source_folder = self.parameterAsString(
            parameters,
            SOURCE_FOLDER,
            context
        )
        source_crs = self.parameterAsCrs(
            parameters,
            SOURCE_CRS,
            context
        )
        output_crs = self.parameterAsCrs(
            parameters,
            OUTPUT_CRS,
            context
        )
        destination_folder = self.parameterAsString(
            parameters,
            DESTINATION_FOLDER,
            context
        )

        list_files = search_files(source_folder + '/', ALLOWED_FORMATS)
        total = len(list_files)
        completed = 0
        feedback.setProgress(0)
        for current_file in list_files:
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Used for error monitoring
            file_read_issue = False
            read_error = ''

            # File parameters
            output_file_name = os.path.basename(current_file)
            destination_file = destination_folder + '/' + output_file_name + '.gpkg'

            if os.path.exists(destination_file):
                # If the file does exist, it will be skipped
                feedback.setProgressText("Current file will be skipped as it exists: {}".format(current_file))
            else:
                # File does not exist, processing starts
                feedback.setProgressText("Current file being processed: {}".format(current_file))
                list_attributes = [
                    QgsField("Longitude", QVariant.Double),
                    QgsField("Latitude", QVariant.Double),
                    QgsField("Elevation", QVariant.Double)
                ]
                new_layer = create_empty_layer("Point", list_attributes, source_crs)
                layer_provider = new_layer.dataProvider()

                with open(current_file) as read_file:
                    while True:
                        try:
                            line = read_file.readline()
                            if not line:
                                # End of file has been reached
                                break
                            new_line = remove_unwanted_chars(line)

                            split = new_line.split(DELIMITER_CHAR)
                            if len(split) == COLUMN_COUNT:
                                x = float(split[X_INDEX])
                                y = float(split[Y_INDEX])
                                elev = float(split[ELEV_INDEX])

                                if elev < ELEV_MIN_THRESHOLD or elev > ELEV_MAX_THRESHOLD:
                                    # Elevation value is not valid
                                    # Feature will be skipped/ignored
                                    continue
                                else:
                                    new_layer.startEditing()
                                    new_point = QgsPointXY(x, y)
                                    new_feature = QgsFeature()
                                    new_feature.setAttributes([x, y, elev])
                                    new_feature.setGeometry(QgsGeometry.fromPointXY(new_point))
                                    layer_provider.addFeatures([new_feature])
                                    new_layer.commitChanges()
                            else:
                                # Line does not consist of the correct number of columns
                                # Feature will be skipped/ignored
                                continue
                        except Exception as e:
                            # Errorenous points will be skipped but reported
                            file_read_issue = True
                            read_error = str(e)
                            continue

                    if file_read_issue:
                        # If there has been an issue when reading a file
                        feedback.setProgressText("Error during processing: {}".format(current_file))
                        feedback.setProgressText("Error message: {}".format(read_error))

                success, created_qgsvectorlayer, msg = create_vector_file(new_layer, destination_file, output_crs)

            completed = completed + 1
            feedback.setProgress(int((completed / total) * 100))

        # Return the results of the algorithm
        return {DESTINATION_FOLDER: destination_folder}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Point Preprocessing'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Preprocessing'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return TerrainPointPreprocessingAlgorithm()
